### ISSUE TITLE
Select a License

### ISSUE THREAD

**Issue by skorasaurus** [opencleveland/RTAHeatMap#6]
Not an immediate priority, but should choose a license. 
There's no hard rule for CFA brigades, but I'd strongly encourage BSD/MIT)

http://choosealicense.com/ is a great resource

**Comment by mbramson** [comment]
Great call.

**Comment by mbramson** [comment]
I chose MIT, should I specify Code for America as the organization?

**Comment by skorasaurus** [comment]
Open Cleveland / Code For America
